import { library } from '@fortawesome/fontawesome-svg-core';

// prettier-ignore
import { faDropbox } from '@fortawesome/free-brands-svg-icons';

// prettier-ignore
import {
  faGear,
  faArrowLeft,
  faPlay,
  faPause,
  faForwardStep,
  faBackwardStep,
  faRotateLeft,
  faArrowRight,
  faCode,
  faCakeSlice,
  faCalendarHeart,
  faCameraWeb,
  faCameraRetro,
  faQuoteLeft,
  faQuoteRight,
  faCastle,
  faCauldron,
  faChampagneGlasses,
  faCommentLines,
  faChurch,
  faFileVideo,
  faHouseBuilding,
  faFlaskRoundPotion,
  faGem,
  faHatWizard,
  faTriangleExclamation,
  faHeartCrack,
  faImages,
  faImagesUser,
  faListCheck,
  faMessageHeart,
  faPeopleArrows,
  faTimes,
  faPhotoFilm,
  faPlateUtensils,
  faRingsWedding,
  faScrollOld,
  faSignalSlash,
  faSignalStream,
  faSparkles,
  faSpinnerThird,
  faStarShooting,
  faTabletScreenButton,
  faTurntable,
  faTrees,
  faUsersViewfinder,
  faVideo,
  faWifi,
  faWreathLaurel,
  faYinYang,
} from '@fortawesome/pro-light-svg-icons';

const buildLibrary = (): void => {
  // prettier-ignore
  library.add(
    // Brands
    faDropbox,
    // Lights
    faGear,
    faArrowLeft,
    faPlay,
    faPause,
    faForwardStep,
    faBackwardStep,
    faRotateLeft,
    faArrowRight,
    faCode,
    faCakeSlice,
    faCalendarHeart,
    faCameraWeb,
    faCameraRetro,
    faQuoteLeft,
    faQuoteRight,
    faCastle,
    faCauldron,
    faChampagneGlasses,
    faCommentLines,
    faChurch,
    faFileVideo,
    faHouseBuilding,
    faFlaskRoundPotion,
    faGem,
    faHatWizard,
    faTriangleExclamation,
    faHeartCrack,
    faImages,
    faImagesUser,
    faListCheck,
    faMessageHeart,
    faPeopleArrows,
    faTimes,
    faPhotoFilm,
    faPlateUtensils,
    faRingsWedding,
    faScrollOld,
    faSignalSlash,
    faSignalStream,
    faSparkles,
    faSpinnerThird,
    faStarShooting,
    faTabletScreenButton,
    faTurntable,
    faTrees,
    faUsersViewfinder,
    faVideo,
    faWifi,
    faWreathLaurel,
    faYinYang,
  );
};

export default { buildLibrary };
