enum ActionTypes {
  SET_ERROR = 'SET_ERROR',
  SET_STATUS = 'SET_STATUS',
  SET_FETCHING = 'SET_FETCHING',
  SET_LOADING = 'SET_LOADING',
  SET_SLIDES = 'SET_SLIDES',
  TO_NEXT = 'TO_NEXT',
  TO_PREV = 'TO_PREV',
  RESTART = 'RESTART',
}

export default ActionTypes;
